name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  TESTS:
    name: Test Project
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'

    steps:
    - uses: actions/checkout@v4

    - name: Setup PDM with Python ${{ matrix.python-version }}
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pdm install

    - name: Test project
      run: pdm test

  DEPLOY:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs: TESTS
    environment:
      name: pypi
      url: https://pypi.org/p/envclass

    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pdm install

    - name: Build project
      run: pdm build

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
