name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/envclass

    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup PDM
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pdm install

    - name: Build project
      run: pdm build

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
